### ISSUE TITLE
Error on installing `LSP-*` servers

### ISSUE THREAD

**Issue by ihodev** [sublimelsp/lsp_utils#24]
```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Ihor\AppData\Roaming\SUBLIM~1\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 22, in run_in_thread
    universal_newlines=True, stderr=subprocess.STDOUT)
  File "./python3.3/subprocess.py", line 578, in check_output
  File "./python3.3/subprocess.py", line 907, in communicate
  File "./python3.3/subprocess.py", line 479, in _eintr_retry_call
  File "./python3.3/encodings/cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 183: character maps to <undefined>

Exception in thread Thread-16:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Ihor\AppData\Roaming\SUBLIM~1\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 22, in run_in_thread
    universal_newlines=True, stderr=subprocess.STDOUT)
  File "./python3.3/subprocess.py", line 578, in check_output
  File "./python3.3/subprocess.py", line 907, in communicate
  File "./python3.3/subprocess.py", line 479, in _eintr_retry_call
  File "./python3.3/encodings/cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 80890: character maps to <undefined>
```

![image](https://user-images.githubusercontent.com/55105210/93181554-432a4500-f741-11ea-90a0-01d089321653.png)

**Comment by ihodev** [comment]
`en-US`, 

Note, this error occurs from time to time when I remove all `LSP-*` folders from ST `Cache` directory to reinstall them

**Comment by rchl** [comment]
I suppose the output of `npm install` is what is triggering the error, depending on what server you are installing.

I only really need the output when running `node --version` and that one shouldn't ever crash on decoding (or maybe it still could when `node` is not available...).

I could probably try decoding manually instead of using `universal_newlines=True`.

**Comment by rwols** [comment]
It could also be the case that while the server is getting installed, it's also started at the same time. On Windows processes hold exclusive file locks so this could screw things up a bit.

**Comment by rchl** [comment]
It doesn't look like that to me. It seems to be just about problem with decoding the output:
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 80890: character maps to <undefined>`

**Comment by rchl** [comment]
I've tested on Windows and was able to reproduce the same crash by reading a file that was encoded either with utf-8 or some ISO encoding.  passing `encoding='utf-8` to `subprocess.check_output` would handle the UTF-8 case but not other strange encodings so went with manual decoding and ignoring unknown characters. I think this could in theory still throw on some strange input but hopefully, it will be good enough.
