### ISSUE TITLE
Still getting odd module import errors after updates

### ISSUE THREAD

**Issue by rwols** [sublimelsp/lsp_utils#27]
```
LSP-json: internal/modules/cjs/loader.js:800
LSP-json:     throw err;
LSP-json:     ^
LSP-json: 
LSP-json: Error: Cannot find module '/home/raoul/.config/sublime-text-3/Cache/LSP-json/language-server/out/node/jsonServerMain.js'
LSP-json:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
LSP-json:     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
LSP-json:     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
LSP-json:     at internal/main/run_main_module.js:17:11 {
LSP-json:   code: 'MODULE_NOT_FOUND',
LSP-json:   requireStack: []
LSP-json: }
```

Use the `needs_update_or_installation` and `install_or_update` classmethods and these problems will likely go away.

**Comment by rchl** [comment]
We've previously identified some problems with ST's file database causing issues but that was only affecting local, sym-linked repo and was related changing branches. It shouldn't trigger for normal uses through PC.

> EDIT: actually I think we need to take care of [sublimelsp/LSP#899](https://github.com/sublimelsp/LSP/issues/899) to get smooth updates.

I can't think of any reason why that would cause such issues.

**Comment by rchl** [comment]
Can you confirm whether by "updates" you mean pulling in git or normal Package Control updates?

**Comment by rwols** [comment]
When updating via Package Control.

I can only make a guess, but I think what happens is something like this:
- ST starts up
- I have a (for instance) a json file
- LSP-json is running
- Package Control checks for updates
- Package Control calls `plugin_unloaded` of LSP-json. This leads to a `shutil.rmtree` I think?
- Package Control replaces LSP-json.sublime-package
- Package Control calls `plugin_loaded` of LSP-json. This spawns a thread that installs various node modules.

In any case, meanwhile, LSP-json is running in my json file. On a linux filesystem this should not matter in theory right? File handles are reference-counted. Ideally LSP would stop the running LSP-json server in plugin_unloaded.

**Comment by rchl** [comment]
Weird.
When it happens next time it might be helpful to see logs from the console to see what exactly has been updated (maybe it's related to `lsp_utils` being upgrade).
