### ISSUE TITLE
The PipClientHandler is registered as a plugin

### ISSUE THREAD

**Issue by rchl** [sublimelsp/lsp_utils#42]
When there are no plugins implementing `PipClientHandler` then that class will be seen as "final" and LSP will try to register it causing this:

```
Failed to register plugin ""
Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/sessions.py", line 558, in _register_plugin_impl
    if client_configs.add_external_config(name, settings, base_file, notify_listener):
  File "/Users/me/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/settings.py", line 37, in add_external_config
    config = ClientConfig.from_sublime_settings(name, s, file)
  File "/Users/me/Library/Application Support/Sublime Text/Packages/LSP/plugin/core/types.py", line 575, in from_sublime_settings
    base = sublime.decode_value(sublime.load_resource(file))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 343, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages//.sublime-settings" not found
```

There is the same problem with `NpmClientHandler` but that one generally has some plugins that use it so in practice it's not likely to trigger the same issue.

One solution I can think of for this is to avoid importing `PipClientHandler` in `/lsp_utils/__init__.py` and instead require plugins to explicitly import it from its file like:

```py
from lsp_utils.pip_client_handler import PipClientHandler
```

Then if nothing imports it then the file will not be parsed and the class won't be visible (assuming that ST only registers root files of a dependency).

**Comment by rchl** [comment]
Fixed with https://github.com/sublimelsp/lsp_utils/pull/45
