### ISSUE TITLE
Updating node issue

### ISSUE THREAD

**Issue by rwols** [sublimelsp/lsp_utils#88]
I have node v12 on the system path.
I have node v14 in the Package Storage path.

LSP-Grammarly wants node v16, but lsp_utils didn't upgrade from the local node v14 to v16

```
LSP-Grammarly: Error: Ignoring system Node.js runtime due to an error. Node.js version requirement failed. Expected minimum: 16.13.0, got 12.13.1.
LSP-Grammarly: Error: Ignoring local Node.js runtime due to an error. Node.js version requirement failed. Expected minimum: 16.13.0, got 14.17.6.
LSP: Resolved Node Runtime for client LSP-Grammarly: None
Unable to start subprocess for grammarly
Traceback (most recent call last):
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/windows.py", line 243, in start_async
    if plugin_class.needs_update_or_installation():
  File "/home/raoul/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "/home/raoul/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 92, in get_server
    'storage_path': cls.storage_path(),
  File "/home/raoul/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 32, in create
    raise Exception('Failed resolving the Node Runtime. Please see Sublime Text console for more information')
Exception: Failed resolving the Node Runtime. Please see Sublime Text console for more information
```

**Comment by rwols** [comment]
Never mind I had to do a `git pull` in my lsp_utils git repository :)
