### ISSUE TITLE
Unable to start LSP-Typescript

### ISSUE THREAD

**Issue by MrMid** [sublimelsp/lsp_utils#92]
Hello, I'm using LSP-Typescript in ST 4137, and recently it stopped being able to start up.

```
Unable to open /home/john/.config/sublime-text-3/Packages/LSP-typescript/LSP-typescript.sublime-settings
Unable to start subprocess for LSP-json
Traceback (most recent call last):
  File "/home/john/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 247, in start_async
    if plugin_class.needs_update_or_installation():
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 108, in get_server
    'skip_npm_install': cls.skip_npm_install,
  File "/home/john/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 33, in create
    raise Exception('Failed resolving the Node Runtime. Please see Sublime Text console for more information')
Exception: Failed resolving the Node Runtime. Please see Sublime Text console for more information
```

I don't remember making any changes corellated to this (in ST, Node, nor my system).

Can you please lead me how to debug this issue?

```
$ node --version
v12.22.10

$ npm --version
6.14.16
```

I'm using nvm to keep node at version 12. I tried setting that to use current version, but that didn't help.

In LSP-typescript.sublime-settings there is:
`"command": ["${node_bin}", "${server_path}", "--stdio"]`

I suppose there could be wrong path in `node_bin`, but how to debug/set that?

Thank you in advance.

**Comment by rchl** [comment]
Transferring to `lsp_utils` to try to improve the messaging in this case.
